pipeline {
    agent any 
    stages {
        stage('Build Application') {
            steps {
                sh 'C:\Users\korkeert\apache-maven-3.9.1-bin\apache-maven-3.9.1\bin\mvn clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
    }
}